
AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: disable


Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Enabled: false

Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

Style/HashSyntax:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/NestedGroups:
  Max: 10

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'

RSpec/ImplicitSubject:
  Enabled: false

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/EmptyLineAfterExampleGroup:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/MultipleSubjects:
  Enabled: false

RSpec/EmptyLineAfterHook:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/EmptyLineAfterSubject:
  Enabled: false

RSpec/FactoryBot/AttributeDefinedStatically:
  Enabled: false

RSpec/ReceiveCounts:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/LetBeforeExamples:
  Enabled: false

RSpec/HooksBeforeExamples:
  Enabled: false
RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/Capybara/CurrentPathExpectation:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/OverwritingSetup:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/FilePath:
  SpecSuffixOnly: true

require:
  - rubocop-rspec