
AllCops:
  TargetRubyVersion: 3.4.2
  SuggestExtensions: false
  NewCops: disable


Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/CyclomaticComplexity:
  Enabled: false

Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

