# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: TestApplication

    pool:
      vmImage: 'Ubuntu-22.04'

    variables:
      rubyVersion: '= 3.3.1'
      bundlerVersion: '2.5.10'

    steps:
    - template: ./pipeline-steps/test-application.yaml
    - template: ./pipeline-steps/publish-tests.yaml
